# Files distributed to students (.ok & tests/ handled automatically)
su20/lab/lab01.d: $(MATERIALS_DST)/su20/lab/lab01/error.jpg
su20/lab/lab01.d: $(MATERIALS_DST)/su20/lab/lab01/numberline_0.png
su20/lab/lab01.d: $(MATERIALS_DST)/su20/lab/lab01/numberline_1.png
su20/lab/lab01.d: $(MATERIALS_DST)/su20/lab/lab01/map.jpg