# Files distributed to students (.ok & tests/ handled automatically)
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/Austen_PrideAndPrejudice.txt
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/player_data.csv
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/salary_data.csv
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/small_srswor_salary.csv
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/large_srswor_salary.csv
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/comparisons.png
su20/lab/lab05.d: $(MATERIALS_DST)/su20/lab/lab05/nacho_reactions.png