# Files distributed to students (.ok & tests/ handled automatically)
su20/lab/lab02.d: $(MATERIALS_DST)/su20/lab/lab02/world_population.csv
su20/lab/lab02.d: $(MATERIALS_DST)/su20/lab/lab02/imdb.csv
su20/lab/lab02.d: $(MATERIALS_DST)/su20/lab/lab02/farmers_markets.csv
su20/lab/lab02.d: $(MATERIALS_DST)/su20/lab/lab02/statement.png