# Files distributed to students (.ok & tests/ handled automatically)
su20/hw/hw04.d: $(MATERIALS_DST)/su20/hw/hw04/burrito.csv
su20/hw/hw04.d: $(MATERIALS_DST)/su20/hw/hw04/burritos_types.csv
su20/hw/hw04.d: $(MATERIALS_DST)/su20/hw/hw04/ratings.csv
su20/hw/hw04.d: $(MATERIALS_DST)/su20/hw/hw04/faculty.csv
su20/hw/hw04.d: $(MATERIALS_DST)/su20/hw/hw04/berkeley_faculty.csv