# Files distributed to students (.ok & tests/ handled automatically)
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/child_mortality.csv
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/countries.csv
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/fertility.csv
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/life_expectancy.csv
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/pew_population_projection.png
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/population.csv
su20/project/project1.d: $(MATERIALS_DST)/su20/project/project1/poverty.csv