# Files distributed to students (.ok & tests/ handled automatically)
su20/hw/hw09.d: $(MATERIALS_DST)/su20/hw/hw09/serial_numbers.csv
su20/hw/hw09.d: $(MATERIALS_DST)/su20/hw/hw09/smallrephist.png
su20/hw/hw09.d: $(MATERIALS_DST)/su20/hw/hw09/reviews.csv
su20/hw/hw09.d: $(MATERIALS_DST)/su20/hw/hw09/more_reviews.csv
su20/hw/hw09.d: $(MATERIALS_DST)/su20/hw/hw09/one_sample.csv