# Files distributed to students (.ok & tests/ handled automatically)
su20/lab/lab04.d: $(MATERIALS_DST)/su20/lab/lab04/raw_compensation.csv
su20/lab/lab04.d: $(MATERIALS_DST)/su20/lab/lab04/movies_by_year.csv
su20/lab/lab04.d: $(MATERIALS_DST)/su20/lab/lab04/apply.png