# Files distributed to students (.ok & tests/ handled automatically)
su20/project/project2.d: $(MATERIALS_DST)/su20/project/project2/movies.csv
su20/project/project2.d: $(MATERIALS_DST)/su20/project/project2/proj3_test_set.csv
su20/project/project2.d: $(MATERIALS_DST)/su20/project/project2/stem.csv
su20/project/project2.d: $(MATERIALS_DST)/su20/project/project2/word_plot.png