# Files distributed to students (.ok & tests/ handled automatically)
su20/hw/hw06.d: $(MATERIALS_DST)/su20/hw/hw06/player_data.csv
su20/hw/hw06.d: $(MATERIALS_DST)/su20/hw/hw06/salary_data.csv
su20/hw/hw06.d: $(MATERIALS_DST)/su20/hw/hw06/sample_salary_data.csv
su20/hw/hw06.d: $(MATERIALS_DST)/su20/hw/hw06/earthquakes_2019.csv