# Files distributed to students (.ok & tests/ handled automatically)
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/world_population.csv
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/array_logarithm.jpg
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/array_multiplication.jpg
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/more_restaurant_bills.csv
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/excel_array.jpg
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/chaining_method_calls.png
su20/lab/lab03.d: $(MATERIALS_DST)/su20/lab/lab03/imdb.csv